### ISSUE TITLE
Server crash upon using ender gaze

### ISSUE THREAD

**Issue by KamiSami** [cleannrooster/Spellblade-Next#2]
Hi, i tried to make comment about this in curseforge but they force me to use their beta crap which wont allow me post any comments for whatever reason... Anyway here is what log says after server crash:

Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "net.spell_engine.entity.SpellProjectile.getSpell()" is null
	at net.spellbladenext.fabric.ExampleModFabric.lambda$static$7(ExampleModFabric.java:99)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:40)
	at net.minecraft.server.MinecraftServer.handler$boj000$onStartTick(MinecraftServer.java:4816)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by cleannrooster** [comment]
Fixed in most recent update.
